# Generated by Django 3.0.3 on 2020-11-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPomyslu',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),

        migrations.CreateModel(
            name='SlowoKluczowe',
            fields=[
                ('slowo_kluczowe', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),

        migrations.CreateModel(
            name='RodzajDecyzji',
            fields=[
                ('rodzaj_decyzji', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),


        migrations.CreateModel(
            name='UstawieniaOceniania',
            fields=[
                ('ustawienia', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('opis', models.TextField(blank=True)),
            ],
        ),

        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=300)),
                ('sso', models.CharField(max_length=9)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='innovation_module.uzytkownik')),
            ],
        ),

        migrations.CreateModel(
            name='CzlonekKomisji',
            fields=[
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='innovation_module.uzytkownik')),
            ],
        ),

        migrations.CreateModel(
            name='ZwyklyUzytkownik',
            fields=[
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='innovation_module.uzytkownik')),
            ],
        ),

        migrations.CreateModel(
            name='Pomysl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematyka', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('planowane_korzysci', models.TextField(blank=True)),
                ('planowane_koszty', models.TextField(blank=True)),
                ('ocena_wazona', models.FloatField(null=True)),
                ('data_dodania', models.DateTimeField('%Y-%m-%d %H:%M:%S')),
                ('data_ostatniej_edycji', models.DateTimeField('%Y-%m-%d %H:%M:%S', null=True)),
                ('slowo_kluczowe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.SlowoKluczowe')),
                ('status_pomyslu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.StatusPomyslu')),
                ('ustawienia_oceniania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.UstawieniaOceniania')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.Uzytkownik')),
            ],
        ),

        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('ocena_liczbowa', models.IntegerField(null=True)),
                ('opis', models.CharField(null=True, max_length=500)),
                ('pomysl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.pomysl')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.uzytkownik')),
            ],
        ),

        migrations.CreateModel(
            name='Decyzja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('uzasadnienie', models.CharField(max_length=1000)),
                ('pomysl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.pomysl')),
                ('czlonek_komisji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.CzlonekKomisji')),
                ('werdykt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.RodzajDecyzji')),
            ],
        ),

        migrations.CreateModel(
            name='Watek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=100)),
                ('data_dodania', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('data_ostatniego_posta', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S', blank=True))
            ],
        ),

        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('watek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.Watek')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.Uzytkownik')),
                ('data_dodania', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'))
            ],
        ),

        migrations.CreateModel(
            name='Zalacznik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pliku', models.CharField(max_length=200)),
                ('data_dodania', models.DateTimeField('%Y-%m-%d %H:%M:%S')),
                ('rozmar', models.IntegerField(null=True))
            ],
        ),

        migrations.CreateModel(
            name='ZalacznikPomyslu',
            fields=[
                ('zalacznik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='innovation_module.Zalacznik')),
                ('pomysl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.Pomysl'))
            ],
        ),

        migrations.CreateModel(
            name='ZalacznikPosta',
            fields=[
                ('zalacznik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='innovation_module.Zalacznik')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.Post'))
            ],
        )
    ]
