# Generated by Django 3.1.3 on 2020-12-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_module', 'mock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomysl',
            name='ocena_wazona',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('ocena_liczbowa', models.IntegerField()),
                ('opis', models.CharField(max_length=500)),
                ('pomysl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.pomysl')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovation_module.uzytkownik')),
            ],
        ),
    ]
