version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    command:
      bash -c "./wait-for-it.sh db:3306 --
      python django_project/manage.py migrate &&
      python django_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    restart: always
    ports:
        - 8000:8000

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: ideas_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
