var app = angular.module('app', [
    'appIdeaAdditionController',
    'appIdeaAdditionService',
    'appIdeasListController',
    'appIdeasListService',
    'appOpinionsListController',
    'appOpinionsListService',
    'appOpinionAdditionController',
    'appOpinionAdditionService',
    'appIdeasFilteredController',
    'appIdeasFilteredService',
    // 'appideasFilteredOdlozonyController',
    // 'appideasFilteredOdlozonyService',
    'appDecisionAdditionController',
    'appDecisionAdditionService',
    'appThreadsListService',
    'appThreadsListController',
    'appPostsListController',
    'appPostsListService',
    'appThreadAdditionController',
    'appThreadAdditionService',
    'appPostAdditionController',
    'appPostAdditionService',
    'appUtils',
    'app'
]);
